version: '3'
services:

  imapbox:
    image: bananaacid/imapbox
    container_name: imapbox
    volumes:
      # change the path './tmp/backup' to your back up folder
      - ./tmp/backup/:/var/imapbox/
      # change the path './tmp/config.cfg' to the config
      - ./tmp/config.cfg:/etc/imapbox/config.cfg

