services:

  imapbox:
    image: bananaacid/imapbox
    container_name: imapbox
    volumes:
      # change the path './tmp/backup' to your back up folder
      - ./tmp/backup/:/var/imapbox/

      # change the path './config.cfg' to the config
      # mounting files: an absolute path is always required
      #- ${PWD}/tmp/config.cfg:/etc/imapbox/config.cfg
      #
      # relative binding works fine
      - type: bind
        source: ./tmp/config.cfg
        target: /etc/imapbox/config.cfg

